apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: roboshop
  labels:
    app: nginx
spec:
  serviceName: mongodb # must point to a headless service
  replicas: 2 # number of pods
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: dockerswaha/mongodb:v1
          ports:
            - containerPort: 27017
              name: web # we can assign port name it is optional
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: manadey # or your own StorageClass
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # Service port
      targetPort: 27017 # Pod containerPort
