apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: roboshop
  labels:
    app: redisdatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisbase
  template:
    metadata:
      labels:
        app: redisbase
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redisbase
  ports:
    - protocol: TCP
      port: 6379      # Service port
      targetPort: 6379 # Pod containerPort

